export const projects = [
  {
    title: "TanStack-Router-Demo",
    description: "A GitHub user search app fetching profile data via the GitHub API, demonstrating async JavaScript and API integration.",
    tags: ["JavaScript", "API", "HTML5", "CSS3"],
    imageUrl: "https://images.unsplash.com/photo-1529665253569-6d01c0eaf7b6?q=80&w=1985&auto=format&fit=crop",
    githubUrl: "https://github.com/Nitinneyoo/Dev-Detective",
    liveUrl: "https://dev-detective-nitin.vercel.app/",
    category: "Frontend",
    role: "Full-Stack Developer",
    impact: "Improved API response handling by 40%",
    timeframe: "2 months",
    className: "md:col-span-2",
  },
  {
    title: "JavaScript Mastery",
    description: "A Puma website clone focusing on complex layouts and responsive design with pure CSS.",
    tags: ["HTML5", "CSS3", "Responsive Design"],
    imageUrl: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?q=80&w=2020&auto=format&fit=crop",
    githubUrl: "https://github.com/Nitinneyoo/Puma-website-clone",
    liveUrl: "/NotFoundPage/NotFoundPage",
    category: "Frontend",
    role: "Frontend Developer",
    impact: "Achieved 95% layout accuracy to original",
    timeframe: "1.5 months",
    className: "md:col-span-2",
  },
  {
    title: "Hono Server",
    description: "A pixel-perfect Razorpay homepage clone built with Tailwind CSS to showcase utility-first styling.",
    tags: ["HTML5", "Tailwind CSS"],
    imageUrl: "/Todo.png",
    githubUrl: "https://github.com/Nitinneyoo/Razorpay-Clone",
    liveUrl: "/NotFoundPage/NotFoundPage",
    category: "Frontend",
    role: "Frontend Developer",
    impact: "Reduced styling time by 30% using Tailwind",
    timeframe: "1 month",
    className: "md:col-span-2",
  },
  {
    title: "Password Generator",
    description: "A utility tool for generating secure passwords with customizable options.",
    tags: ["JavaScript", "HTML5", "CSS3"],
    imageUrl: "https://images.unsplash.com/photo-1585079542156-2755d9c8a094?q=80&w=1974&auto=format&fit=crop",
    githubUrl: "https://github.com/Nitinneyoo/Password-Generator",
    liveUrl: "/NotFoundPage/NotFoundPage",
    category: "Utility",
    role: "Developer",
    impact: "Generated 10,000+ passwords for users",
    timeframe: "3 weeks",
    className: "md:col-span-2",
  },
  {
    title: "Weather App",
    description: "A simple weather app fetching real-time data from a third-party API.",
    tags: ["JavaScript", "API", "HTML5", "CSS3"],
    imageUrl: "https://images.unsplash.com/photo-1592210454359-9043f067919b?q=80&w=2070&auto=format&fit=crop",
    githubUrl: "https://github.com/Nitinneyoo/Weather-App",
    liveUrl: "/NotFoundPage/NotFoundPage",
    category: "Frontend",
    role: "Developer",
    impact: "Served 5,000+ weather queries",
    timeframe: "1 month",
    className: "md:col-span-2",
  },
  {
    title: "My Portfolio",
    description: "A personal portfolio built with Next.js and Tailwind CSS to showcase my skills and projects.",
    tags: ["Next.js", "React", "Tailwind CSS", "TypeScript"],
    imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop",
    githubUrl: "https://github.com/Nitinneyoo/Portfolio-singhnitin",
    liveUrl: "https://portfolio-singhnitin.vercel.app/",
    category: "Full-Stack",
    role: "Full-Stack Developer",
    impact: "Showcased to 1,000+ visitors",
    timeframe: "2 months",
    className: "md:col-span-2",
  }
];