/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SkillSectionRouteRouteImport } from './routes/SkillSection/route'
import { Route as ProjectSectionRouteRouteImport } from './routes/ProjectSection/route'
import { Route as ContactSectionRouteRouteImport } from './routes/ContactSection/route'
import { Route as AboutSectionRouteRouteImport } from './routes/AboutSection/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotFoundPageNotFoundPageRouteImport } from './routes/NotFoundPage/NotFoundPage'
import { Route as FooterPagesTermsServicesPageRouteRouteImport } from './routes/FooterPages/TermsServicesPage/route'
import { Route as FooterPagesPrivacyPolicyPageRouteRouteImport } from './routes/FooterPages/PrivacyPolicyPage/route'
import { Route as FooterPagesFaqSectionRouteRouteImport } from './routes/FooterPages/FaqSection/route'
import { Route as FooterPagesChangeLogPageRouteRouteImport } from './routes/FooterPages/ChangeLogPage/route'
import { Route as FooterPagesBlogSectionRouteRouteImport } from './routes/FooterPages/BlogSection/route'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillSectionRouteRoute = SkillSectionRouteRouteImport.update({
  id: '/SkillSection',
  path: '/SkillSection',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSectionRouteRoute = ProjectSectionRouteRouteImport.update({
  id: '/ProjectSection',
  path: '/ProjectSection',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactSectionRouteRoute = ContactSectionRouteRouteImport.update({
  id: '/ContactSection',
  path: '/ContactSection',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSectionRouteRoute = AboutSectionRouteRouteImport.update({
  id: '/AboutSection',
  path: '/AboutSection',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundPageNotFoundPageRoute =
  NotFoundPageNotFoundPageRouteImport.update({
    id: '/NotFoundPage/NotFoundPage',
    path: '/NotFoundPage/NotFoundPage',
    getParentRoute: () => rootRouteImport,
  } as any)
const FooterPagesTermsServicesPageRouteRoute =
  FooterPagesTermsServicesPageRouteRouteImport.update({
    id: '/FooterPages/TermsServicesPage',
    path: '/FooterPages/TermsServicesPage',
    getParentRoute: () => rootRouteImport,
  } as any)
const FooterPagesPrivacyPolicyPageRouteRoute =
  FooterPagesPrivacyPolicyPageRouteRouteImport.update({
    id: '/FooterPages/PrivacyPolicyPage',
    path: '/FooterPages/PrivacyPolicyPage',
    getParentRoute: () => rootRouteImport,
  } as any)
const FooterPagesFaqSectionRouteRoute =
  FooterPagesFaqSectionRouteRouteImport.update({
    id: '/FooterPages/FaqSection',
    path: '/FooterPages/FaqSection',
    getParentRoute: () => rootRouteImport,
  } as any)
const FooterPagesChangeLogPageRouteRoute =
  FooterPagesChangeLogPageRouteRouteImport.update({
    id: '/FooterPages/ChangeLogPage',
    path: '/FooterPages/ChangeLogPage',
    getParentRoute: () => rootRouteImport,
  } as any)
const FooterPagesBlogSectionRouteRoute =
  FooterPagesBlogSectionRouteRouteImport.update({
    id: '/FooterPages/BlogSection',
    path: '/FooterPages/BlogSection',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/AboutSection': typeof AboutSectionRouteRoute
  '/ContactSection': typeof ContactSectionRouteRoute
  '/ProjectSection': typeof ProjectSectionRouteRoute
  '/SkillSection': typeof SkillSectionRouteRoute
  '/about': typeof AboutRoute
  '/FooterPages/BlogSection': typeof FooterPagesBlogSectionRouteRoute
  '/FooterPages/ChangeLogPage': typeof FooterPagesChangeLogPageRouteRoute
  '/FooterPages/FaqSection': typeof FooterPagesFaqSectionRouteRoute
  '/FooterPages/PrivacyPolicyPage': typeof FooterPagesPrivacyPolicyPageRouteRoute
  '/FooterPages/TermsServicesPage': typeof FooterPagesTermsServicesPageRouteRoute
  '/NotFoundPage/NotFoundPage': typeof NotFoundPageNotFoundPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/AboutSection': typeof AboutSectionRouteRoute
  '/ContactSection': typeof ContactSectionRouteRoute
  '/ProjectSection': typeof ProjectSectionRouteRoute
  '/SkillSection': typeof SkillSectionRouteRoute
  '/about': typeof AboutRoute
  '/FooterPages/BlogSection': typeof FooterPagesBlogSectionRouteRoute
  '/FooterPages/ChangeLogPage': typeof FooterPagesChangeLogPageRouteRoute
  '/FooterPages/FaqSection': typeof FooterPagesFaqSectionRouteRoute
  '/FooterPages/PrivacyPolicyPage': typeof FooterPagesPrivacyPolicyPageRouteRoute
  '/FooterPages/TermsServicesPage': typeof FooterPagesTermsServicesPageRouteRoute
  '/NotFoundPage/NotFoundPage': typeof NotFoundPageNotFoundPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/AboutSection': typeof AboutSectionRouteRoute
  '/ContactSection': typeof ContactSectionRouteRoute
  '/ProjectSection': typeof ProjectSectionRouteRoute
  '/SkillSection': typeof SkillSectionRouteRoute
  '/about': typeof AboutRoute
  '/FooterPages/BlogSection': typeof FooterPagesBlogSectionRouteRoute
  '/FooterPages/ChangeLogPage': typeof FooterPagesChangeLogPageRouteRoute
  '/FooterPages/FaqSection': typeof FooterPagesFaqSectionRouteRoute
  '/FooterPages/PrivacyPolicyPage': typeof FooterPagesPrivacyPolicyPageRouteRoute
  '/FooterPages/TermsServicesPage': typeof FooterPagesTermsServicesPageRouteRoute
  '/NotFoundPage/NotFoundPage': typeof NotFoundPageNotFoundPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/AboutSection'
    | '/ContactSection'
    | '/ProjectSection'
    | '/SkillSection'
    | '/about'
    | '/FooterPages/BlogSection'
    | '/FooterPages/ChangeLogPage'
    | '/FooterPages/FaqSection'
    | '/FooterPages/PrivacyPolicyPage'
    | '/FooterPages/TermsServicesPage'
    | '/NotFoundPage/NotFoundPage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/AboutSection'
    | '/ContactSection'
    | '/ProjectSection'
    | '/SkillSection'
    | '/about'
    | '/FooterPages/BlogSection'
    | '/FooterPages/ChangeLogPage'
    | '/FooterPages/FaqSection'
    | '/FooterPages/PrivacyPolicyPage'
    | '/FooterPages/TermsServicesPage'
    | '/NotFoundPage/NotFoundPage'
  id:
    | '__root__'
    | '/'
    | '/AboutSection'
    | '/ContactSection'
    | '/ProjectSection'
    | '/SkillSection'
    | '/about'
    | '/FooterPages/BlogSection'
    | '/FooterPages/ChangeLogPage'
    | '/FooterPages/FaqSection'
    | '/FooterPages/PrivacyPolicyPage'
    | '/FooterPages/TermsServicesPage'
    | '/NotFoundPage/NotFoundPage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutSectionRouteRoute: typeof AboutSectionRouteRoute
  ContactSectionRouteRoute: typeof ContactSectionRouteRoute
  ProjectSectionRouteRoute: typeof ProjectSectionRouteRoute
  SkillSectionRouteRoute: typeof SkillSectionRouteRoute
  AboutRoute: typeof AboutRoute
  FooterPagesBlogSectionRouteRoute: typeof FooterPagesBlogSectionRouteRoute
  FooterPagesChangeLogPageRouteRoute: typeof FooterPagesChangeLogPageRouteRoute
  FooterPagesFaqSectionRouteRoute: typeof FooterPagesFaqSectionRouteRoute
  FooterPagesPrivacyPolicyPageRouteRoute: typeof FooterPagesPrivacyPolicyPageRouteRoute
  FooterPagesTermsServicesPageRouteRoute: typeof FooterPagesTermsServicesPageRouteRoute
  NotFoundPageNotFoundPageRoute: typeof NotFoundPageNotFoundPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SkillSection': {
      id: '/SkillSection'
      path: '/SkillSection'
      fullPath: '/SkillSection'
      preLoaderRoute: typeof SkillSectionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ProjectSection': {
      id: '/ProjectSection'
      path: '/ProjectSection'
      fullPath: '/ProjectSection'
      preLoaderRoute: typeof ProjectSectionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ContactSection': {
      id: '/ContactSection'
      path: '/ContactSection'
      fullPath: '/ContactSection'
      preLoaderRoute: typeof ContactSectionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AboutSection': {
      id: '/AboutSection'
      path: '/AboutSection'
      fullPath: '/AboutSection'
      preLoaderRoute: typeof AboutSectionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/NotFoundPage/NotFoundPage': {
      id: '/NotFoundPage/NotFoundPage'
      path: '/NotFoundPage/NotFoundPage'
      fullPath: '/NotFoundPage/NotFoundPage'
      preLoaderRoute: typeof NotFoundPageNotFoundPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FooterPages/TermsServicesPage': {
      id: '/FooterPages/TermsServicesPage'
      path: '/FooterPages/TermsServicesPage'
      fullPath: '/FooterPages/TermsServicesPage'
      preLoaderRoute: typeof FooterPagesTermsServicesPageRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FooterPages/PrivacyPolicyPage': {
      id: '/FooterPages/PrivacyPolicyPage'
      path: '/FooterPages/PrivacyPolicyPage'
      fullPath: '/FooterPages/PrivacyPolicyPage'
      preLoaderRoute: typeof FooterPagesPrivacyPolicyPageRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FooterPages/FaqSection': {
      id: '/FooterPages/FaqSection'
      path: '/FooterPages/FaqSection'
      fullPath: '/FooterPages/FaqSection'
      preLoaderRoute: typeof FooterPagesFaqSectionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FooterPages/ChangeLogPage': {
      id: '/FooterPages/ChangeLogPage'
      path: '/FooterPages/ChangeLogPage'
      fullPath: '/FooterPages/ChangeLogPage'
      preLoaderRoute: typeof FooterPagesChangeLogPageRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FooterPages/BlogSection': {
      id: '/FooterPages/BlogSection'
      path: '/FooterPages/BlogSection'
      fullPath: '/FooterPages/BlogSection'
      preLoaderRoute: typeof FooterPagesBlogSectionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutSectionRouteRoute: AboutSectionRouteRoute,
  ContactSectionRouteRoute: ContactSectionRouteRoute,
  ProjectSectionRouteRoute: ProjectSectionRouteRoute,
  SkillSectionRouteRoute: SkillSectionRouteRoute,
  AboutRoute: AboutRoute,
  FooterPagesBlogSectionRouteRoute: FooterPagesBlogSectionRouteRoute,
  FooterPagesChangeLogPageRouteRoute: FooterPagesChangeLogPageRouteRoute,
  FooterPagesFaqSectionRouteRoute: FooterPagesFaqSectionRouteRoute,
  FooterPagesPrivacyPolicyPageRouteRoute:
    FooterPagesPrivacyPolicyPageRouteRoute,
  FooterPagesTermsServicesPageRouteRoute:
    FooterPagesTermsServicesPageRouteRoute,
  NotFoundPageNotFoundPageRoute: NotFoundPageNotFoundPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
